[package]
name = "operating-system-project"
version = "0.1.0"
authors = ["Juuso Tuononen <jutuon@outlook.com>"]
edition = "2018"
publish = false

[dependencies]
pic8259 = { git = "https://github.com/jutuon/pic8259" }

# Crates.io
vga-framebuffer = "0.7.4"
volatile = "0.2.5"
x86 = "0.12.0"
seq-macro = "0.1.2"
arraydeque = { version = "0.4", default-features = false }
bitflags = "1.0.4"
